import { useState, useEffect, useRef } from "react";
import { S } from "../../data/catalogue.js";
import Btn from "../../components/common/Btn.jsx";

export const MerchantAgreement=({go,onAgree})=>(
 <div style={{minHeight:"100vh",background:"#f7f7f8",overflowY:"auto"}}><div style={{background:"rgba(18,18,18,0.98)",borderBottom:"1px solid #1a1a1a",position:"sticky",top:0,zIndex:100,padding:"0 24px",display:"flex",alignItems:"center",height:56}}><button onClick={()=>go(S.REG)} style={{background:"none",border:"none",color:"#555",cursor:"pointer",fontSize:13,marginRight:16}}>← Back</button><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,background:"linear-gradient(135deg,#fe2c55,#ff6b35)",borderRadius:7,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14}}></div><span style={{fontFamily:"'TikTok Sans',sans-serif",fontWeight:800,fontSize:16,color:"#111"}}>ShopTok<span style={{color:"#fe2c55"}}>.</span></span></div></div><div style={{maxWidth:760,margin:"0 auto",padding:"40px 20px 60px"}}><div style={{textAlign:"center",marginBottom:36}}><div style={{display:"inline-flex",alignItems:"center",gap:6,background:"rgba(254,44,85,0.1)",border:"1px solid rgba(254,44,85,0.25)",color:"#fe2c55",fontSize:11,fontWeight:700,padding:"5px 14px",borderRadius:100,marginBottom:16,textTransform:"uppercase",letterSpacing:"0.5px"}}>Legal Document</div><h1 style={{fontFamily:"'TikTok Sans',sans-serif",fontSize:32,fontWeight:900,color:"#111",letterSpacing:"-1px",marginBottom:10}}>Merchant <span style={{color:"#fe2c55"}}>Partner</span>Agreement</h1><p style={{color:"#555",fontSize:14,lineHeight:1.6,maxWidth:500,margin:"0 auto 20px"}}>Please read this agreement carefully before becoming a merchant partner on the ShopTok platform.</p><div style={{display:"flex",justifyContent:"center",gap:20,flexWrap:"wrap"}}>
 {[["","Effective: June 2025"],["","Version 2.0"],["","ShopTok Pakistan"]].map(([e,t])=>(
 <span key={t} style={{fontSize:12,color:"#444",display:"flex",alignItems:"center",gap:5}}><span>{e}</span>{t}</span>
 ))}
 </div></div><div style={{background:"#ffffff",border:"1px solid rgba(254,44,85,0.25)",borderRadius:14,padding:24,marginBottom:28,borderLeft:"4px solid #fe2c55"}}><p style={{fontSize:14,color:"#888",lineHeight:1.8}}>Welcome to become a merchant partner of the <strong style={{color:"#111"}}>ShopTok platform</strong>. In order to maintain the normal operation of the platform and protect the rights and interests of you and consumers, we have formulated the following merchant entry agreement.</p></div>
 {[
 {num:1,title:"Admission Requirements",clauses:["Merchants must provide true and valid personal information, contact information and other relevant certification materials, and ensure that the information provided is true, accurate, complete, legal and valid.","Merchants should sell products produced or supplied by suppliers provided by the platform, and bear legal responsibilities and economic losses arising from the sale of products not provided by platform suppliers.","Merchants must have sufficient capital, technology, service and other capabilities to meet the needs of consumers and bear corresponding commercial risks."]},
 {num:2,title:"Cooperation Method",clauses:["Merchants can submit an application through the online application system provided by the ShopTok platform, and can officially become a cooperative merchant of the platform after being approved by the platform.","The goods sold by the merchant are provided by the platform supplier, and the merchant should ensure that the goods provided are consistent with the actual goods.","Merchants can conduct commodity management, order processing, transaction settlement and other operations through the sales management system provided by the platform.","Merchants must abide by the platform's Seller Policy and Privacy Policy to ensure their own legal and compliant operations, and bear legal responsibility and economic losses arising from violations."]},
 {num:3,title:"Commodity Information & Service Quality",clauses:["Merchants need to provide true, accurate and complete product information, including but not limited to product name, price, specification, description, picture and other information, and ensure that the product information is consistent with the actual product.","Merchants should provide goods and services that comply with national laws and regulations and platform requirements to ensure the quality and safety of goods and services.","Merchants should respond to consumers' inquiries, complaints and other information in a timely manner, and actively solve related problems to ensure that consumers' rights and interests are protected."]},
 {num:4,title:"Commission & Settlement",clauses:["The merchant pays the commission according to the commission standard stipulated by the platform, and ensures the legitimacy and accuracy of the commission.","The platform will settle the commission according to the agreed settlement cycle based on the transaction volume and sales data of the merchant."]}
 ].map(sec=>(
 <div key={sec.num} style={{background:"#ffffff",border:"1px solid #1a1a1a",borderRadius:14,marginBottom:16,overflow:"hidden"}}><div style={{display:"flex",alignItems:"center",gap:14,padding:"18px 22px",borderBottom:"1px solid #1a1a1a",background:"rgba(0,0,0,0.02)"}}><div style={{width:34,height:34,borderRadius:9,background:"linear-gradient(135deg,#fe2c55,#ff6b35)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:800,color:"#fff",flexShrink:0}}>{sec.num}</div><h3 style={{fontSize:16,fontWeight:700,color:"#111"}}>{sec.title}</h3></div>
 {sec.clauses.map((c,i)=>(
 <div key={i} style={{display:"flex",gap:14,padding:"14px 22px",borderBottom:i<sec.clauses.length-1?"1px solid #141414":"none"}}><div style={{width:22,height:22,borderRadius:6,background:"#ffffff",border:"1px solid #e5e5e5",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:"#fe2c55",flexShrink:0,marginTop:2}}>{i+1}</div><p style={{fontSize:13,color:"#888",lineHeight:1.75}}>{c}</p></div>
 ))}
 </div>
 ))}
 <div style={{background:"#ffffff",border:"1px solid #1a1a1a",borderRadius:14,padding:28,textAlign:"center",marginTop:8}}><h3 style={{fontSize:18,fontWeight:700,color:"#111",marginBottom:8}}>Ready to Join ShopTok? </h3><p style={{fontSize:13,color:"#555",marginBottom:22,lineHeight:1.6}}>By clicking "I Agree and Continue", you confirm that you have read and agree to all terms of this Merchant Partner Agreement.</p><div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}><Btn onClick={onAgree}>I Agree and Continue</Btn><Btn variant="ghost" onClick={()=>go(S.REG)}>Go Back</Btn></div></div></div></div>
);

export default MerchantAgreement;
